// Golden-file regression test for core/orbit_enumerator_slow.h.
//
// For each (family, q, N) combo with family ∈ {full, cyclic, extfield},
// q ∈ {2, 3}, N ∈ {1, 2, 3, 4}, we instantiate `OrbitEnumeratorSlow<Problem>`
// in-process, call `Search()`, and compare to a checked-in golden cert under
// `search/testdata/orbit_enumerator/<family>_q<q>_n<N>.pb.txt`. The goldens are
// regenerated by `//search:testdata_generator_main`.

#include "search/orbit_enumerator_slow.h"

#include <string>

#include <google/protobuf/util/message_differencer.h>
#include <gtest/gtest.h>

#include "core/certificate.pb.h"
#include "core/proto_io.h"
#include "problems/cyclic/problem.h"
#include "problems/extfield/problem.h"
#include "problems/full/problem.h"
#include "problems/matrix/problem.h"

namespace {

template <class Problem> void CheckAgainstGolden() {
  const typename Problem::SymmetryGroup group;
  const OrbitEnumeratorSlow<Problem> enumerator(&group);
  pb::Certificate computed = enumerator.Search();

  const std::string path =
      "search/testdata/orbit_enumerator/" + Problem::Name() + ".pb.txt";
  pb::Certificate golden = ReadProtoFromFile<pb::Certificate>(path);

  google::protobuf::util::MessageDifferencer diff;
  std::string report;
  diff.ReportDifferencesToString(&report);
  EXPECT_TRUE(diff.Compare(golden, computed)) << report;
}

// full
TEST(OrbitEnumeratorSlowTest, FullQ2) {
  CheckAgainstGolden<full::Problem<2, 1, 1>>();
  CheckAgainstGolden<full::Problem<2, 1, 2>>();
  CheckAgainstGolden<full::Problem<2, 1, 3>>();
  CheckAgainstGolden<full::Problem<2, 1, 4>>();
}
TEST(OrbitEnumeratorSlowTest, FullQ3) {
  CheckAgainstGolden<full::Problem<3, 1, 1>>();
  CheckAgainstGolden<full::Problem<3, 1, 2>>();
  CheckAgainstGolden<full::Problem<3, 1, 3>>();
}
TEST(OrbitEnumeratorSlowTest, FullQ4) {
  CheckAgainstGolden<full::Problem<2, 2, 1>>();
  CheckAgainstGolden<full::Problem<2, 2, 2>>();
  CheckAgainstGolden<full::Problem<2, 2, 3>>();
}
TEST(OrbitEnumeratorSlowTest, FullQ5) {
  CheckAgainstGolden<full::Problem<5, 1, 1>>();
  CheckAgainstGolden<full::Problem<5, 1, 2>>();
  CheckAgainstGolden<full::Problem<5, 1, 3>>();
}
TEST(OrbitEnumeratorSlowTest, FullQ7) {
  CheckAgainstGolden<full::Problem<7, 1, 1>>();
  CheckAgainstGolden<full::Problem<7, 1, 2>>();
  CheckAgainstGolden<full::Problem<7, 1, 3>>();
}
TEST(OrbitEnumeratorSlowTest, FullQ8) {
  CheckAgainstGolden<full::Problem<2, 3, 1>>();
  CheckAgainstGolden<full::Problem<2, 3, 2>>();
  CheckAgainstGolden<full::Problem<2, 3, 3>>();
}
TEST(OrbitEnumeratorSlowTest, FullQ9) {
  CheckAgainstGolden<full::Problem<3, 2, 1>>();
  CheckAgainstGolden<full::Problem<3, 2, 2>>();
  CheckAgainstGolden<full::Problem<3, 2, 3>>();
}

// cyclic
TEST(OrbitEnumeratorSlowTest, CyclicQ2) {
  CheckAgainstGolden<cyclic::Problem<2, 1, 1>>();
  CheckAgainstGolden<cyclic::Problem<2, 1, 2>>();
  CheckAgainstGolden<cyclic::Problem<2, 1, 3>>();
  CheckAgainstGolden<cyclic::Problem<2, 1, 4>>();
}
TEST(OrbitEnumeratorSlowTest, CyclicQ3) {
  CheckAgainstGolden<cyclic::Problem<3, 1, 1>>();
  CheckAgainstGolden<cyclic::Problem<3, 1, 2>>();
  CheckAgainstGolden<cyclic::Problem<3, 1, 3>>();
  CheckAgainstGolden<cyclic::Problem<3, 1, 4>>();
}
TEST(OrbitEnumeratorSlowTest, CyclicQ4) {
  CheckAgainstGolden<cyclic::Problem<2, 2, 1>>();
  CheckAgainstGolden<cyclic::Problem<2, 2, 2>>();
  CheckAgainstGolden<cyclic::Problem<2, 2, 3>>();
  CheckAgainstGolden<cyclic::Problem<2, 2, 4>>();
}
TEST(OrbitEnumeratorSlowTest, CyclicQ5) {
  CheckAgainstGolden<cyclic::Problem<5, 1, 1>>();
  CheckAgainstGolden<cyclic::Problem<5, 1, 2>>();
  CheckAgainstGolden<cyclic::Problem<5, 1, 3>>();
  CheckAgainstGolden<cyclic::Problem<5, 1, 4>>();
}
TEST(OrbitEnumeratorSlowTest, CyclicQ7) {
  CheckAgainstGolden<cyclic::Problem<7, 1, 1>>();
  CheckAgainstGolden<cyclic::Problem<7, 1, 2>>();
  CheckAgainstGolden<cyclic::Problem<7, 1, 3>>();
  CheckAgainstGolden<cyclic::Problem<7, 1, 4>>();
}
TEST(OrbitEnumeratorSlowTest, CyclicQ8) {
  CheckAgainstGolden<cyclic::Problem<2, 3, 1>>();
  CheckAgainstGolden<cyclic::Problem<2, 3, 2>>();
  CheckAgainstGolden<cyclic::Problem<2, 3, 3>>();
}
TEST(OrbitEnumeratorSlowTest, CyclicQ9) {
  CheckAgainstGolden<cyclic::Problem<3, 2, 1>>();
  CheckAgainstGolden<cyclic::Problem<3, 2, 2>>();
  CheckAgainstGolden<cyclic::Problem<3, 2, 3>>();
}

// extfield
TEST(OrbitEnumeratorSlowTest, ExtfieldQ2) {
  CheckAgainstGolden<extfield::Problem<2, 1, 1>>();
  CheckAgainstGolden<extfield::Problem<2, 1, 2>>();
  CheckAgainstGolden<extfield::Problem<2, 1, 3>>();
  CheckAgainstGolden<extfield::Problem<2, 1, 4>>();
}
TEST(OrbitEnumeratorSlowTest, ExtfieldQ3) {
  CheckAgainstGolden<extfield::Problem<3, 1, 1>>();
  CheckAgainstGolden<extfield::Problem<3, 1, 2>>();
  CheckAgainstGolden<extfield::Problem<3, 1, 3>>();
  CheckAgainstGolden<extfield::Problem<3, 1, 4>>();
}
TEST(OrbitEnumeratorSlowTest, ExtfieldQ4) {
  CheckAgainstGolden<extfield::Problem<2, 2, 1>>();
  CheckAgainstGolden<extfield::Problem<2, 2, 2>>();
  CheckAgainstGolden<extfield::Problem<2, 2, 3>>();
  CheckAgainstGolden<extfield::Problem<2, 2, 4>>();
}
TEST(OrbitEnumeratorSlowTest, ExtfieldQ5) {
  CheckAgainstGolden<extfield::Problem<5, 1, 1>>();
  CheckAgainstGolden<extfield::Problem<5, 1, 2>>();
  CheckAgainstGolden<extfield::Problem<5, 1, 3>>();
  CheckAgainstGolden<extfield::Problem<5, 1, 4>>();
}
TEST(OrbitEnumeratorSlowTest, ExtfieldQ7) {
  CheckAgainstGolden<extfield::Problem<7, 1, 1>>();
  CheckAgainstGolden<extfield::Problem<7, 1, 2>>();
  CheckAgainstGolden<extfield::Problem<7, 1, 3>>();
  CheckAgainstGolden<extfield::Problem<7, 1, 4>>();
}
TEST(OrbitEnumeratorSlowTest, ExtfieldQ8) {
  CheckAgainstGolden<extfield::Problem<2, 3, 1>>();
  CheckAgainstGolden<extfield::Problem<2, 3, 2>>();
  CheckAgainstGolden<extfield::Problem<2, 3, 3>>();
}
TEST(OrbitEnumeratorSlowTest, ExtfieldQ9) {
  CheckAgainstGolden<extfield::Problem<3, 2, 1>>();
  CheckAgainstGolden<extfield::Problem<3, 2, 2>>();
  CheckAgainstGolden<extfield::Problem<3, 2, 3>>();
}

// matrix
TEST(OrbitEnumeratorSlowTest, MatrixQ2) {
  CheckAgainstGolden<matrix::Problem<2, 1, 1, 2, 3>>();
  CheckAgainstGolden<matrix::Problem<2, 1, 1, 3, 2>>();
  CheckAgainstGolden<matrix::Problem<2, 1, 2, 1, 3>>();
  CheckAgainstGolden<matrix::Problem<2, 1, 2, 2, 2>>();
  CheckAgainstGolden<matrix::Problem<2, 1, 2, 2, 3>>();
  CheckAgainstGolden<matrix::Problem<2, 1, 2, 3, 1>>();
  CheckAgainstGolden<matrix::Problem<2, 1, 2, 3, 2>>();
  CheckAgainstGolden<matrix::Problem<2, 1, 2, 3, 3>>();
  CheckAgainstGolden<matrix::Problem<2, 1, 3, 1, 2>>();
  CheckAgainstGolden<matrix::Problem<2, 1, 3, 2, 1>>();
  CheckAgainstGolden<matrix::Problem<2, 1, 3, 2, 2>>();
  CheckAgainstGolden<matrix::Problem<2, 1, 3, 2, 3>>();
  CheckAgainstGolden<matrix::Problem<2, 1, 3, 3, 2>>();
  CheckAgainstGolden<matrix::Problem<2, 1, 3, 3, 3>>();
}

} // namespace
