// Golden-file regression test for core/rank_lower_bound_computer.h.
//
// For each (family, q, N) combo we load the enumerator golden from
// search/testdata/orbit_enumerator/, then run ProcessOrbits three times in a
// chain (basic; basic+degenerate; all three techniques), comparing the
// certificate after each step to the matching golden under
// search/testdata/rank_lower_bound_{basic,basic_degenerate,all}/. The goldens
// are regenerated by //search:testdata_generator_main.

#include "search/rank_lower_bound_computer.h"

#include <string>

#include <google/protobuf/util/message_differencer.h>
#include <gtest/gtest.h>

#include "core/certificate.pb.h"
#include "core/proto_io.h"
#include "problems/cyclic/problem.h"
#include "problems/extfield/problem.h"
#include "problems/full/problem.h"
#include "problems/matrix/problem.h"

namespace {

void ExpectEqual(const pb::Certificate &golden,
                 const pb::Certificate &computed) {
  google::protobuf::util::MessageDifferencer diff;
  std::string report;
  diff.ReportDifferencesToString(&report);
  EXPECT_TRUE(diff.Compare(golden, computed)) << report;
}

template <class Problem> void CheckAgainstGolden() {
  const std::string filename = Problem::Name() + ".pb.txt";
  pb::Certificate cert = ReadProtoFromFile<pb::Certificate>(
      "search/testdata/orbit_enumerator/" + filename);

  ProcessOrbits<Problem>({.basic_method = true,
                          .degenerate_method = false,
                          .backtracking_step_limit = 0},
                         /*output_path=*/"", &cert);
  ExpectEqual(ReadProtoFromFile<pb::Certificate>(
                  "search/testdata/rank_lower_bound_basic/" + filename),
              cert);

  ProcessOrbits<Problem>({.basic_method = true,
                          .degenerate_method = true,
                          .backtracking_step_limit = 0},
                         /*output_path=*/"", &cert);
  ExpectEqual(
      ReadProtoFromFile<pb::Certificate>(
          "search/testdata/rank_lower_bound_basic_degenerate/" + filename),
      cert);

  ProcessOrbits<Problem>({.basic_method = true,
                          .degenerate_method = true,
                          .backtracking_step_limit = 100'000},
                         /*output_path=*/"", &cert);
  ExpectEqual(ReadProtoFromFile<pb::Certificate>(
                  "search/testdata/rank_lower_bound_all/" + filename),
              cert);
}

TEST(RankLowerBoundComputerTest, FullQ2) {
  CheckAgainstGolden<full::Problem<2, 1, 1>>();
  CheckAgainstGolden<full::Problem<2, 1, 2>>();
  CheckAgainstGolden<full::Problem<2, 1, 3>>();
  CheckAgainstGolden<full::Problem<2, 1, 4>>();
}
TEST(RankLowerBoundComputerTest, FullQ3) {
  CheckAgainstGolden<full::Problem<3, 1, 1>>();
  CheckAgainstGolden<full::Problem<3, 1, 2>>();
  CheckAgainstGolden<full::Problem<3, 1, 3>>();
}
TEST(RankLowerBoundComputerTest, FullQ4) {
  CheckAgainstGolden<full::Problem<2, 2, 1>>();
  CheckAgainstGolden<full::Problem<2, 2, 2>>();
  CheckAgainstGolden<full::Problem<2, 2, 3>>();
}
TEST(RankLowerBoundComputerTest, FullQ5) {
  CheckAgainstGolden<full::Problem<5, 1, 1>>();
  CheckAgainstGolden<full::Problem<5, 1, 2>>();
  CheckAgainstGolden<full::Problem<5, 1, 3>>();
}
TEST(RankLowerBoundComputerTest, FullQ7) {
  CheckAgainstGolden<full::Problem<7, 1, 1>>();
  CheckAgainstGolden<full::Problem<7, 1, 2>>();
  CheckAgainstGolden<full::Problem<7, 1, 3>>();
}
TEST(RankLowerBoundComputerTest, FullQ8) {
  CheckAgainstGolden<full::Problem<2, 3, 1>>();
  CheckAgainstGolden<full::Problem<2, 3, 2>>();
  CheckAgainstGolden<full::Problem<2, 3, 3>>();
}
TEST(RankLowerBoundComputerTest, FullQ9) {
  CheckAgainstGolden<full::Problem<3, 2, 1>>();
  CheckAgainstGolden<full::Problem<3, 2, 2>>();
  CheckAgainstGolden<full::Problem<3, 2, 3>>();
}

TEST(RankLowerBoundComputerTest, CyclicQ2) {
  CheckAgainstGolden<cyclic::Problem<2, 1, 1>>();
  CheckAgainstGolden<cyclic::Problem<2, 1, 2>>();
  CheckAgainstGolden<cyclic::Problem<2, 1, 3>>();
  CheckAgainstGolden<cyclic::Problem<2, 1, 4>>();
}
TEST(RankLowerBoundComputerTest, CyclicQ3) {
  CheckAgainstGolden<cyclic::Problem<3, 1, 1>>();
  CheckAgainstGolden<cyclic::Problem<3, 1, 2>>();
  CheckAgainstGolden<cyclic::Problem<3, 1, 3>>();
  CheckAgainstGolden<cyclic::Problem<3, 1, 4>>();
}
TEST(RankLowerBoundComputerTest, CyclicQ4) {
  CheckAgainstGolden<cyclic::Problem<2, 2, 1>>();
  CheckAgainstGolden<cyclic::Problem<2, 2, 2>>();
  CheckAgainstGolden<cyclic::Problem<2, 2, 3>>();
  CheckAgainstGolden<cyclic::Problem<2, 2, 4>>();
}
TEST(RankLowerBoundComputerTest, CyclicQ5) {
  CheckAgainstGolden<cyclic::Problem<5, 1, 1>>();
  CheckAgainstGolden<cyclic::Problem<5, 1, 2>>();
  CheckAgainstGolden<cyclic::Problem<5, 1, 3>>();
  CheckAgainstGolden<cyclic::Problem<5, 1, 4>>();
}
TEST(RankLowerBoundComputerTest, CyclicQ7) {
  CheckAgainstGolden<cyclic::Problem<7, 1, 1>>();
  CheckAgainstGolden<cyclic::Problem<7, 1, 2>>();
  CheckAgainstGolden<cyclic::Problem<7, 1, 3>>();
  CheckAgainstGolden<cyclic::Problem<7, 1, 4>>();
}
TEST(RankLowerBoundComputerTest, CyclicQ8) {
  CheckAgainstGolden<cyclic::Problem<2, 3, 1>>();
  CheckAgainstGolden<cyclic::Problem<2, 3, 2>>();
  CheckAgainstGolden<cyclic::Problem<2, 3, 3>>();
}
TEST(RankLowerBoundComputerTest, CyclicQ9) {
  CheckAgainstGolden<cyclic::Problem<3, 2, 1>>();
  CheckAgainstGolden<cyclic::Problem<3, 2, 2>>();
  CheckAgainstGolden<cyclic::Problem<3, 2, 3>>();
}

TEST(RankLowerBoundComputerTest, ExtfieldQ2) {
  CheckAgainstGolden<extfield::Problem<2, 1, 1>>();
  CheckAgainstGolden<extfield::Problem<2, 1, 2>>();
  CheckAgainstGolden<extfield::Problem<2, 1, 3>>();
  CheckAgainstGolden<extfield::Problem<2, 1, 4>>();
}
TEST(RankLowerBoundComputerTest, ExtfieldQ3) {
  CheckAgainstGolden<extfield::Problem<3, 1, 1>>();
  CheckAgainstGolden<extfield::Problem<3, 1, 2>>();
  CheckAgainstGolden<extfield::Problem<3, 1, 3>>();
  CheckAgainstGolden<extfield::Problem<3, 1, 4>>();
}
TEST(RankLowerBoundComputerTest, ExtfieldQ4) {
  CheckAgainstGolden<extfield::Problem<2, 2, 1>>();
  CheckAgainstGolden<extfield::Problem<2, 2, 2>>();
  CheckAgainstGolden<extfield::Problem<2, 2, 3>>();
  CheckAgainstGolden<extfield::Problem<2, 2, 4>>();
}
TEST(RankLowerBoundComputerTest, ExtfieldQ5) {
  CheckAgainstGolden<extfield::Problem<5, 1, 1>>();
  CheckAgainstGolden<extfield::Problem<5, 1, 2>>();
  CheckAgainstGolden<extfield::Problem<5, 1, 3>>();
  CheckAgainstGolden<extfield::Problem<5, 1, 4>>();
}
TEST(RankLowerBoundComputerTest, ExtfieldQ7) {
  CheckAgainstGolden<extfield::Problem<7, 1, 1>>();
  CheckAgainstGolden<extfield::Problem<7, 1, 2>>();
  CheckAgainstGolden<extfield::Problem<7, 1, 3>>();
  CheckAgainstGolden<extfield::Problem<7, 1, 4>>();
}
TEST(RankLowerBoundComputerTest, ExtfieldQ8) {
  CheckAgainstGolden<extfield::Problem<2, 3, 1>>();
  CheckAgainstGolden<extfield::Problem<2, 3, 2>>();
  CheckAgainstGolden<extfield::Problem<2, 3, 3>>();
}
TEST(RankLowerBoundComputerTest, ExtfieldQ9) {
  CheckAgainstGolden<extfield::Problem<3, 2, 1>>();
  CheckAgainstGolden<extfield::Problem<3, 2, 2>>();
  CheckAgainstGolden<extfield::Problem<3, 2, 3>>();
}

// matrix
TEST(RankLowerBoundComputerTest, MatrixQ2) {
  CheckAgainstGolden<matrix::Problem<2, 1, 1, 2, 3>>();
  CheckAgainstGolden<matrix::Problem<2, 1, 1, 3, 2>>();
  CheckAgainstGolden<matrix::Problem<2, 1, 2, 1, 3>>();
  CheckAgainstGolden<matrix::Problem<2, 1, 2, 2, 2>>();
  CheckAgainstGolden<matrix::Problem<2, 1, 2, 2, 3>>();
  CheckAgainstGolden<matrix::Problem<2, 1, 2, 3, 1>>();
  CheckAgainstGolden<matrix::Problem<2, 1, 2, 3, 2>>();
  CheckAgainstGolden<matrix::Problem<2, 1, 2, 3, 3>>();
  CheckAgainstGolden<matrix::Problem<2, 1, 3, 1, 2>>();
  CheckAgainstGolden<matrix::Problem<2, 1, 3, 2, 1>>();
  CheckAgainstGolden<matrix::Problem<2, 1, 3, 2, 2>>();
  CheckAgainstGolden<matrix::Problem<2, 1, 3, 2, 3>>();
}

} // namespace
